[UXE-3263] refactor: edge app create page selectors radio and switch changed to new blocks
aziontech/azion-console-kit pull request #1160
Opened 2024-05-17 21:10 UTC by peterpaulo-azion

## Pull Request

### What is the new behavior introduced by this PR?

* edge app create page selectors radio and switch changed to new blocks
	* Radio
	* Switch
 	
### Does this PR introduce breaking changes?
- [ ] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

<img width="815" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/109550332/fef51dae-e14d-416a-92fe-cc1bdc793e54">
<img width="815" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/109550332/37c9afab-3a86-427b-a8b1-ac61a6858ad6">
<img width="815" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/109550332/3f791f01-6501-42eb-9e52-62ccea1a8f58">

### Does it have a link on Figma?

[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=nH0s5eLy1GvDX7wn-0)

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [ ] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [ ] Commits are tagged with the right word (fix, feat, test, etc)
- [ ] User inputs are sanitized/protected against malicious attacks
- [ ] Tags are added to the PR

#### These changes were tested on the following browsers:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-05-20 13:59 UTC, matheus-sunderhus commented on src/services/edge-application-services/create-edge-application-service.js
> +    minimum_tls_version: payload.minimumTlsVersion,
A remoção do parse, irá causar bug no edge application para o campo de minimum tls. Ver Pr de 4 semanas atrás nesta linha de código.

2024-05-20 14:00 UTC, matheus-sunderhus commented on src/services/edge-application-services/edit-edge-application-service.js
> +    minimum_tls_version: payload.minimumTlsVersion,
Verificar edição para garantir que não está causando problemas. Olhar pr de 4 semanas nesta linha.

2024-05-20 14:00 UTC, matheus-sunderhus commented on src/services/edge-application-services/load-edge-application-service.js
> -    minimumTlsVersion: body.minimum_tls_version || 'none',
não remover essa parte, pois ele existe para que o campo consiga colocar uma opção e não fique como vazio.

2024-05-20 14:01 UTC, matheus-sunderhus requested changes
Ocasiona bug ao remover o parse e validação do minumumTlsVersion.

2024-05-20 14:02 UTC, matheus-sunderhus commented on src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
> +            placeholder="None"
ajustar placeholder. Colocar Select a minimum TLS Version.

2024-05-20 14:07 UTC, matheus-sunderhus commented on src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
> -    { label: 'None', value: 'none' },
reverter essa parte.

2024-05-21 19:06 UTC, peterpaulo-azion commented on src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
> +  const isHttp3Protocol = computed(() => deliveryProtocol.value === 'http3')
Boa sacada! Valeu!

2024-05-21 19:19 UTC, matheus-sunderhus approved these changes

2024-05-21 19:32 UTC, william-tome commented on src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
> +  ])
Sugestão: trocar para constantes ao invés de computed, já que esses dados são estáticos e não precisam ser reativos.

2024-05-21 19:38 UTC, william-tome approved these changes

2024-05-22 14:04 UTC, lucasmendes21 approved these changes

2024-05-22 14:05 UTC, merged