[QA-1939] feat: add cypress login test
aziontech/azion-console-kit pull request #1174
Opened 2024-05-22 19:33 UTC by andradepradorafael

## Pull Request

### What is the new behavior introduced by this PR?
The new behavior introduced by this PR is the addition of an end-to-end (e2e) automated login test using Cypress within the Azion Console Kit. This test verifies the login functionality efficiently and reliably by following the Arrange, Act, Assert (AAA) notation.

### Does this PR introduce breaking changes?
- [X] No
- [ ] Yes

2024-05-22 19:36 UTC, matheus-sunderhus commented on .gitignore
> +cypress.env.json
cypress.env.*
!cypress.env.exmaple.json

2024-05-22 19:37 UTC, matheus-sunderhus commented on .gitignore
> +cypress.env.json
deixar o padrão de exclusão mais genérico e o de inclusão mais específico 👍🏻

2024-05-22 19:37 UTC, matheus-sunderhus reviewed
Ajuste de git ignore

2024-05-22 19:37 UTC, andradepradorafael commented on .gitignore
> +cypress.env.json
Done!

2024-05-22 19:45 UTC, matheus-sunderhus commented on .gitignore
> +!cypress.env.exmaple.json
typo, faltou o A no exAmple

2024-05-22 19:56 UTC, andradepradorafael commented on .gitignore
> +!cypress.env.exmaple.json
Done!

2024-05-22 19:58 UTC, matheus-sunderhus approved these changes
LGTM

2024-05-23 13:00 UTC, william-tome approved these changes

2024-05-24 20:46 UTC, alisson-marcelo-azion requested changes
E2E tests are failing

2024-05-27 11:59 UTC, alisson-marcelo-azion approved these changes

2024-05-27 12:05 UTC, higorjasonduarte approved these changes

2024-05-27 12:07 UTC, merged