[UXE-3328] bug: profile menu position
aziontech/azion-console-kit pull request #1248
Opened 2024-06-06 13:57 UTC by cesaroeduardo

## Bug fix

### Explain what was fixed and the correct behavior.
The account menu gets lost in the anchoring and appears incorrectly after scrolling the screen, a vertical positioning value was added next to the style so that it stays fixed at that point on the screen, I tested via passthrough and class and it didn't work. returned the expected behavior, just via style.

### Does this PR introduce UI changes? Add a video or screenshots here.

https://github.com/aziontech/azion-console-kit/assets/44036260/c5c1cb57-71ec-40ac-9155-2e792823a537

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [x] Application responsiveness was tested to different screen sizes
- [ ] New tests are added to prevent the same issue from happening again
- [x] UI changes are validated by a team designer
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Safari

2024-06-06 14:16 UTC, matheus-sunderhus commented on src/templates/profile-block/index.vue
> +    style="position: fixed !important; top: 46px"
não seria possível passar isso via :pt usando classes tailwind (fixed top-12)?
root: { class: 'w-[280px] pb-2 pt-0' },
root: { class: 'w-[280px] pb-2 pt-0 fixed top-12' },

2024-06-06 14:16 UTC, matheus-sunderhus requested changes
Verificar uso de classes tailwind e pt props, para evitar uso de estilo fora do tailwind.

2024-06-06 14:29 UTC, cesaroeduardo commented on src/templates/profile-block/index.vue
> +    style="position: fixed !important; top: 46px"
Como coloquei ali na descrição, foi a primeira alternativa, por algum motivo colocando no passtrought ao clicar ele sobe o scroll que é uma interação meio estranha, colocando via style não teve esse problema, por isso mantive.

2024-06-06 14:39 UTC, cesaroeduardo commented on src/templates/profile-block/index.vue
> +    style="position: fixed !important; top: 46px"
https://github.com/aziontech/azion-console-kit/assets/44036260/cbadd42d-08bf-40c7-a554-c82d58ebe2cf

2024-06-07 13:04 UTC, matheus-sunderhus commented on src/templates/profile-block/index.vue
> +    style="position: fixed !important; top: 46px"
enconrei esse ajuste aqui:
![image](https://github.com/aziontech/azion-console-kit/assets/101186721/4662cbe2-29e9-46ce-9b63-5fcd3ca4b6f5)

colocando isso no código consegui manter o o menu junto do header.

2024-06-07 13:07 UTC, matheus-sunderhus approved these changes

2024-06-07 13:07 UTC, merged