[UXE-3775] test: e2e domains main crud
aziontech/azion-console-kit pull request #1413
Opened 2024-07-03 15:20 UTC by peterpaulo-azion

## Pull Request

### What is the new behavior introduced by this PR?
* linter utils
* test crud domains
* selectors added
* data-testid in fieldDropdown component

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] Safari

2024-07-03 16:19 UTC, alisson-marcelo-azion commented on cypress/e2e/domains.cy.js
> +
Provável que todo esse trecho se torne uma função auxiliar ou comando nos próximos PRs nesse teste. Mas por ora está bom 😉

2024-07-03 16:20 UTC, alisson-marcelo-azion commented on cypress/e2e/domains.cy.js
> +    cy.verifyToast('Resource successfully deleted')
Aqui poderia usar o cy.deleteProduct()

2024-07-03 16:20 UTC, alisson-marcelo-azion commented on cypress/e2e/domains.cy.js
> +    cy.get(selectors.domains.dialogTitle).should('have.text', 'Domain has been created')
cy.VerifyToast aqui ?

2024-07-03 16:37 UTC, alisson-marcelo-azion requested changes

2024-07-03 16:37 UTC, alisson-marcelo-azion commented on cypress/support/selectors.js
> +  edgeDns: {
Não entendo porque o linter não havia bloqueado isso 😬

2024-07-03 16:59 UTC, peterpaulo-azion commented on cypress/e2e/domains.cy.js
> +    cy.get(selectors.domains.dialogTitle).should('have.text', 'Domain has been created')
Não, aqui eu estou verificando o título de um modal/dialog.

2024-07-03 18:25 UTC, alisson-marcelo-azion commented on cypress/e2e/domains.cy.js
> +    cy.get(selectors.domains.dialogTitle).should('have.text', 'Domain has been created')
Eu não conhecia isso 😮 : 
![Screenshot 2024-07-03 at 15 24 36](https://github.com/aziontech/azion-console-kit/assets/81633584/b590c476-509f-4112-9326-a0bb434dfd01)

2024-07-04 12:04 UTC, william-tome approved these changes

2024-07-04 12:16 UTC, alisson-marcelo-azion approved these changes

2024-07-04 12:17 UTC, merged