[UXE-4155] feat: clicking on payment history should open the invoice details
aziontech/azion-console-kit pull request #1519
Opened 2024-07-22 13:38 UTC by pauloSF0

## Pull Request

### What is the new behavior introduced by this PR?
feat: clicking on payment history should open the invoice details

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

https://github.com/user-attachments/assets/ea518605-4a32-4dc6-ba53-34b681bc65ee

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-07-22 13:42 UTC, matheus-sunderhus commented on src/templates/list-table-block/index.vue
> +      type: Boolean
o bloco do projeto que é genérico não deve ter propriedades de uma tela específica .

2024-07-22 13:42 UTC, matheus-sunderhus commented on src/templates/list-table-block/index.vue
> +  const navigateToInvoiceDetails = (item) => {
esse código de billing não deve estar dentro do bloco genérico do projeto.

2024-07-22 13:43 UTC, matheus-sunderhus requested changes
Major changes.

2024-07-22 13:46 UTC, matheus-sunderhus commented on src/templates/list-table-block/index.vue
> +  }
remover lógica do list-table-block , pensar em como resolver isso passando um serviço ou escutando um evento na View de billing que usa esse bloco.

2024-07-22 13:49 UTC, HerbertJulio commented on src/templates/list-table-block/index.vue
>    }
Recomendo simplificar os cenários para apenas dois: um onde o clique na linha redireciona para uma URL e outro onde executa uma ação. Sugiro remover o método `navigateToInvoiceDetails` e, em vez disso, verificar se o usuário forneceu a prop `editPagePath`. Se essa prop não estiver presente, o clique deve acionar um evento (emit) que será capturado pela view, permitindo que a view decida a ação a ser tomada.

2024-07-22 18:04 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +    emit('event-go-to-edit', item)
*Dúvida*
Precisa realmente criar um evento pra ser chamado no mesmo contexto? Por que não adicionar o "item" ao evento que já existe?

2024-07-22 18:11 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +    emit('event-go-to-edit', item)
Esse primeiro evento de emit é para o tracker então acho que seria ideal ter outro evento ao invés usar o de tracker

2024-07-22 18:34 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +    emit('event-go-to-edit', item)
O nome do evento que já existe é genérico o suficiente pra não ser exclusivo de tracking. Não vejo motivo pra criar mais um, mas não é impeditivo no meu ponto de vista.

2024-07-22 19:08 UTC, HerbertJulio commented on src/templates/list-table-block/index.vue
>      } else if (props.enableEditClick) {
```suggestion
  const editItemSelected = ({ data: item }) => {
    emit('on-before-go-to-edit')
    if (props.editInDrawer) {
      props.editInDrawer(item)
      return
    }
    if (props.enableEditClick) {
        emit('event-go-to-edit', item)
        router.push({ path: `${props.editPagePath}/${item.id}` })
        return
    }
```

2024-07-22 20:56 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
>      } else if (props.enableEditClick) {
Dessa forma não da certo

2024-07-23 14:15 UTC, matheus-sunderhus commented on src/templates/list-table-block/index.vue
> +    emit('event-go-to-edit', item)
Concordo com o Will, podemos adicionar o item no evento já existente sem comprometer o tracking, visto que ambos os eventos tem relação a notificar quando vamos para edit.

2024-07-23 21:34 UTC, lucasmendes21 commented on src/views/Billing/BillsView.vue
> +    @event-go-to-edit="goToEnvoiceDetails"
O nome do evento poderia ser ClickingToEdit ou apenas ClickToEdit. não é impeditivo.

2024-07-23 21:34 UTC, lucasmendes21 commented on src/views/Billing/BillsView.vue
> +      const routeParams = { billId: invoiceNumber }
Aqui poderia ser apenas uma variável. Ex: `const routeParams = { billId: item.invoiceNumber.content }`

2024-07-23 21:35 UTC, lucasmendes21 approved these changes

2024-07-24 14:12 UTC, matheus-sunderhus submitted a review, later dismissed
LGTM

2024-07-24 14:46 UTC, HerbertJulio commented on src/views/Billing/BillsView.vue
> +    if (item.invoiceUrl && item.invoiceNumber) {
Recomendo remover o `invoiceUrl` já que precisamos somente do `invoiceNumber`

2024-07-24 16:37 UTC, HerbertJulio approved these changes

2024-07-24 17:41 UTC, matheus-sunderhus approved these changes

2024-07-24 18:31 UTC, merged