[UXE-3455] fix: screen goes white when clicking on active marketplace category
aziontech/azion-console-kit pull request #1537
Opened 2024-07-26 14:09 UTC by pauloSF0

## Bug fix

### Explain what was fixed and the correct behavior.

fix: screen goes white when clicking on active marketplace category

### Does this PR introduce UI changes? Add a video or screenshots here.

https://github.com/user-attachments/assets/13b917f8-9141-422d-9f2d-a486db9cae05

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [x] Application responsiveness was tested to different screen sizes
- [ ] New tests are added to prevent the same issue from happening again
- [ ] UI changes are validated by a team designer
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-07-26 18:50 UTC, william-tome requested changes

2024-07-26 18:50 UTC, william-tome commented on src/views/Marketplace/MarketplaceHomeView.vue
> +  const currentCategory = ref({ name: 'All', code: 'all' })
Isso não me parece muito correto. Ter duas variáveis pra controlar o mesmo fluxo?

Pelo que entendi sobre o bug, é preciso verificar o que está alterando o valor do selectedCategory, já que ela possui valores na montagem do componente. Não está claro pra mim que isso soluciona o problema.

2024-07-29 11:07 UTC, pauloSF0 commented on src/views/Marketplace/MarketplaceHomeView.vue
> +  const currentCategory = ref({ name: 'All', code: 'all' })
O problema detectado era que, ao clicar no mesmo menu que já estava ativo, o componente do PrimeVue retornava um valor null, gerando o erro mencionado. Para solucionar essa questão, implementei uma variável para armazenar a categoria selecionada no momento. Dessa forma, caso o componente retorne um valor null, tenho um registro da categoria previamente selecionada, evitando o problema ocorrido.

2024-07-29 11:11 UTC, william-tome commented on src/views/Marketplace/MarketplaceHomeView.vue
> +  const currentCategory = ref({ name: 'All', code: 'all' })
Isso eu entendi pelo código. Avalia se não é melhor desabilitar o click nesse elemento ou tenta entender melhor o motivo desse valor estar sendo retornado como nulo.

2024-07-29 12:42 UTC, william-tome commented on src/views/Marketplace/MarketplaceHomeView.vue
> +
```suggestion
  const disabledOption = ({ code }) => code === selectedCategory.value?.code

```

2024-07-29 14:07 UTC, HerbertJulio approved these changes

2024-07-29 14:09 UTC, lucasmendes21 approved these changes

2024-07-29 14:12 UTC, merged