[UXE-4204] fix:  waf tunning does not display attack logs
aziontech/azion-console-kit pull request #1547
Opened 2024-07-29 17:47 UTC by pauloSF0

## Bug fix

### Explain what was fixed and the correct behavior.
[UXE-4204] fix:  waf tunning does not display attack logs

### Does this PR introduce UI changes? Add a video or screenshots here.

Uploading Gravação de Tela 2024-07-29 às 14.37.53.mov…

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [x] Application responsiveness was tested to different screen sizes
- [ ] New tests are added to prevent the same issue from happening again
- [ ] UI changes are validated by a team designer
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-07-30 14:29 UTC, aloisio-m-bastian approved these changes
LGTM

2024-07-30 15:18 UTC, william-tome requested changes
Verificar documentação e remover watches desnecessários

https://v3.primevue.org/datatable/

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +      default: false
```suggestion
```

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +      default: false
Default de booleano é sempre "false"
 Sugestão de escrita simplificada:
```suggestion
    cleanSelectData: Boolean
```

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +    dataFilted: {
```suggestion
    dataFiltered: {
```

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +  )
Duplicado
```suggestion
```

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +  })
Esse watch é necessário? o componente não tem um evento pra update de model??

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +  )
Isso é necessário? O componente não tem um evento de atualização de filtro?

2024-07-30 15:18 UTC, william-tome commented on src/templates/list-table-block/index.vue
> +  )
Não sei se esse watch é necessário

2024-07-30 17:01 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +      default: false
done

2024-07-30 17:03 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +      default: false
Prefiro manter o padrão com `type: Boolean` que estamos acostumados a utilizar e, além disso, essa abordagem mantém a consistência com outras propriedades semelhantes.

2024-07-30 17:03 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +    dataFilted: {
done

2024-07-30 17:04 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +  )
done

2024-07-30 17:17 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +  )
No caso do Tunning, a abordagem difere das demais telas, uma vez que o `request` é realizado no componente List Block em todas as outras telas. Porém, o Tunning é um produto de filtro, e os dados só estarão disponíveis após o usuário aplicar um filtro. Além disso, o `request` é feito na `view` e somente depois os dados são repassados para o componente por meio da `props`.

2024-07-30 17:17 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +  )
done

2024-07-30 17:20 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +  })
Não entendi muito bem qual é o problema essa parte do código.

2024-07-30 17:31 UTC, HerbertJulio commented on src/templates/list-table-block/index.vue
@pauloSF0 realmente é necessário criar 4 watch's? o component não tem nenhum tipo de event updated?

2024-07-30 17:42 UTC, HerbertJulio commented on src/templates/list-table-block/index.vue
https://v3.primevue.org/datatable/#api.datatable.emits

2024-07-31 09:52 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
> +  })
done

2024-07-31 09:52 UTC, pauloSF0 commented on src/templates/list-table-block/index.vue
done

2024-07-31 19:07 UTC, william-tome submitted a review, later dismissed

2024-07-31 21:02 UTC, HerbertJulio approved these changes

2024-08-01 13:10 UTC, william-tome approved these changes

2024-08-01 13:19 UTC, merged