[UXE-4335] fix: update rules engine list response phase after success creation
aziontech/azion-console-kit pull request #1574
Opened 2024-08-01 19:37 UTC by matheus-sunderhus

## Bug fix

### Explain what was fixed and the correct behavior.
Ensure that  the Edge application - Rules Engine - Response phase list is updated after a successfully creation .
- Fix empty search results message
- fix flaky test implementation of load-your-service-plan-service, by using vitest fake timers instead of the production code using JS Date Class.
- remove dead code inside list-template-block by removing unused slot 

### Does this PR introduce UI changes? Add a video or screenshots here.
No.
<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [ ] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [ ] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [ ] New tests are added to prevent the same issue from happening again
- [ ] UI changes are validated by a team designer
- [ ] Code is formatted and linted
- [ ] Tags are added to the PR

#### These changes were tested on the following browsers:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-08-01 20:33 UTC, william-tome commented on src/views/EdgeApplicationsRulesEngine/ListView.vue
> +  const phaseOptions = ref(['Request phase', 'Response phase'])
Não precisa ser reativo pelo que vi.

```suggestion
  const PHASE_OPTIONS = ['Request phase', 'Response phase']
```

2024-08-01 20:41 UTC, HerbertJulio commented on src/views/EdgeApplicationsRulesEngine/ListView.vue
> +  })
Sugestão: O componente `SelectButton`, que recebe a propriedade `selectedPhase`, possui eventos (`emits`) que possivelmente podem ser utilizados em vez de um `watch`. 
Recomendo analisar a possibilidade de utilizar esses eventos para melhorar a implementação: https://v3.primevue.org/selectbutton/#api.selectbutton.emits

2024-08-02 12:10 UTC, william-tome requested changes
Alteração simples, mas que economiza memória para o usuário.

2024-08-02 12:19 UTC, HerbertJulio requested changes
Waiting for change

2024-08-02 13:06 UTC, matheus-sunderhus commented on src/views/EdgeApplicationsRulesEngine/ListView.vue
> +  })
Obrigado pela dica, realmente funcionou sem o watch e foi possível remover isso da view.

2024-08-02 13:14 UTC, HerbertJulio approved these changes

2024-08-02 13:23 UTC, william-tome approved these changes

2024-08-02 13:34 UTC, merged