[UXE-3366] fix: status code 400 when creating allowed rule by tuning
aziontech/azion-console-kit pull request #1579
Opened 2024-08-02 16:15 UTC by pauloSF0

## Pull Request

### What is the new behavior introduced by this PR?

fix: status code 400 when creating allowed rule by tuning

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-08-02 16:48 UTC, HerbertJulio commented on src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
> +  }
Utilizar algo assim não resolve MAP_MATCH_ZONES[zone] || defaultZone ?

2024-08-02 17:34 UTC, matheus-sunderhus commented on src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
> +  }
bom ponto, acredito que fica mais legível também

2024-08-02 17:37 UTC, matheus-sunderhus requested changes
checkAndReturnDefault has a request change to improve code implementation.

2024-08-05 13:15 UTC, lucasmendes21 approved these changes

2024-08-05 14:15 UTC, merged