[UXE-4291] fix: adjust load data in dropdown network list
aziontech/azion-console-kit pull request #1590
Opened 2024-08-06 12:24 UTC by lucasmendes21

## Bug fix
adjust load data in dropdown network list

### Explain what was fixed and the correct behavior.
loading the data selected in the dropdown

### Does this PR introduce UI changes? Add a video or screenshots here.
https://jam.dev/c/42f9b1b4-2d9c-4692-a915-cfa086fd5731

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [ ] New tests are added to prevent the same issue from happening again
- [ ] UI changes are validated by a team designer
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-08-06 12:47 UTC, PabloDiehl submitted a review, later dismissed

2024-08-06 16:36 UTC, vinigfer commented
How about adding some tests?

2024-08-06 16:45 UTC, matheus-sunderhus commented on src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
need to add an  unit test to this fixing scenario

2024-08-06 16:46 UTC, matheus-sunderhus requested changes
Add unit test case

2024-08-13 17:11 UTC, vinigfer approved these changes

2024-08-14 17:05 UTC, william-tome approved these changes

2024-08-14 17:21 UTC, merged