[UXE-4356] feat: add secrets segment variables in the workflows
aziontech/azion-console-kit pull request #1597
Opened 2024-08-07 12:21 UTC by pauloSF0

## Pull Request

### What is the new behavior introduced by this PR?

feat: add secrets segment variables in the workflows

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-08-07 12:58 UTC, vinigfer commented on README.md
> +VITE_PROD_SEGMENT_TOKEN=pk_test_yourProdTokenHere
Acho que podemos remover o `pk_test_` aqui. Os tokens do segment não seguem nenhum padrão que nem o Stripe
```suggestion
VITE_STAGE_SEGMENT_TOKEN=yourStageTokenHere
VITE_PROD_SEGMENT_TOKEN=yourProdTokenHere
```

2024-08-07 13:03 UTC, vinigfer commented on src/plugins/factories/analytics-tracking-factory.js
> +  stage: 'STAGE_SEGMENT_TOKEN',
Aqui não deveria ser `VITE_STAGE_SEGMENT_TOKEN` (e equivalente para prod)?

2024-08-07 13:35 UTC, pauloSF0 commented on README.md
> +VITE_PROD_SEGMENT_TOKEN=pk_test_yourProdTokenHere
Done

2024-08-07 17:07 UTC, matheus-sunderhus commented on src/plugins/analytics/AnalyticsTrackerAdapter.js
> +    const segmentToken = environment[env] || 'VITE_STAGE_SEGMENT_TOKEN'
remove iss de dentro do adaptador, faça a injeção via construtor o token. Mover essa parte para um helper e via AnalyticsTrackerAdapterPlugin.js, passar o valor pelo construtor.

2024-08-07 17:07 UTC, matheus-sunderhus commented on src/plugins/analytics/AnalyticsTrackerAdapter.js
> +    const segmentToken = environment[env] || 'VITE_STAGE_SEGMENT_TOKEN'
esse método deve apenas verificar se tem ou não algum token para evitar o track, ser executado.

2024-08-07 17:08 UTC, matheus-sunderhus requested changes
usar AnalyticsTrackerAdapterPlugin para injetar token já pronto para a classe. Refactor do método validateToken.

2024-08-07 17:11 UTC, matheus-sunderhus commented on src/plugins/analytics/AnalyticsTrackerAdapter.js
> +    const segmentToken = environment[env] || 'VITE_STAGE_SEGMENT_TOKEN'
Esse novo comportamento deve conter um teste unitário :
AnalyticsTrackerAdapter.test.js -> adicionar cenário onde não se tem um segment token e verificar se o tracking não é chamado.

2024-08-08 13:11 UTC, HerbertJulio commented
@matheus-sunderhus Acredito que temos que centralizar os tokens por tipo é não por ambiente.
Algo onde tenhamos somente um token que identifique o ambiente de stage ou prod;

2024-08-08 13:16 UTC, matheus-sunderhus commented on src/plugins/factories/segment-handler-token-factory.js
> +function segmentHandlerToken(environment) {
factories no projeto usam o prefixo make.
ajustar para nomenclatura padrão:
makeSegmentToken

2024-08-08 13:20 UTC, matheus-sunderhus commented on src/plugins/factories/segment-handler-token-factory.js
> +  const token = secretVariable[environment] || 'VITE_STAGE_SEGMENT_TOKEN'
simplificar para usar apenas um VITE_SEGMENT_TOKEN. Podemos injetar o valor de stage, produção via workflow e no nosso repositório, dessa forma não precisamos calcular isso aqui dentro também.

dessa forma, podemos usar apenas a linha abaixo:

const segmentToken = import.meta.env[VITE_SEGMENT_TOKEN]

2024-08-08 13:21 UTC, matheus-sunderhus commented on src/plugins/factories/segment-handler-token-factory.js
> +  const token = secretVariable[environment] || 'VITE_STAGE_SEGMENT_TOKEN'
Antes de realizar o merge desta atividade, alinhar com o nosso manager para ele adicionar os 2 valores de secrets a serem usados no workflow para essa mesma variável de VITE_SEGMENT_TOKEN

2024-08-08 13:22 UTC, matheus-sunderhus requested changes
required changes to simplify secrets management.

2024-08-08 13:29 UTC, matheus-sunderhus commented on src/plugins/analytics/AnalyticsTrackerAdapter.js
> +    return true
return !!this.#token

2024-08-08 14:42 UTC, peterpaulo-azion commented on README.md
> +* `VITE_STAGE_SEGMENT_TOKEN`: This is your Segment token for the staging environment. It is used to authenticate API requests in the staging environment to track and analyze user interactions and eve
A seção do README acima está se referindo somente ao STRIPE, é necessário criar uma outra seção com ## voltada somente ao SEGMENT.

2024-08-08 16:51 UTC, pauloSF0 commented on README.md
> +* `VITE_STAGE_SEGMENT_TOKEN`: This is your Segment token for the staging environment. It is used to authenticate API requests in the staging environment to track and analyze user interactions and eve
Valeu por avisar.
Done

2024-08-08 16:52 UTC, pauloSF0 commented on src/plugins/factories/segment-handler-token-factory.js
> +  const token = secretVariable[environment] || 'VITE_STAGE_SEGMENT_TOKEN'
done

2024-08-08 17:51 UTC, HerbertJulio commented on README.md
> +
Acho que esse trecho deveria ser somente sobre o `VITE_SEGMENT_TOKEN`

2024-08-08 17:59 UTC, HerbertJulio commented on src/plugins/factories/analytics-tracking-factory.js
> +  production: 'VITE_PROD_SEGMENT_TOKEN'
Você removeu das actions, então essas variáveis não existem mais `VITE_STAGE_SEGMENT_TOKEN` e `VITE_PROD_SEGMENT_TOKEN`.

2024-08-08 18:21 UTC, vinigfer commented on src/plugins/factories/segment-handler-token-factory.js
> +  const token = secretVariable[environment] || 'VITE_STAGE_SEGMENT_TOKEN'
> adicionar os 2 valores de secrets a serem

Já foram adicionados e os nomes colocados na issue do jira

2024-08-08 18:23 UTC, vinigfer commented on src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
> +const makeSut = (segmentToken = 'VITE_STAGE_SEGMENT_TOKEN') => {
Não estamos mais usando stage ou prod certo?
```suggestion
const makeSut = (segmentToken = 'VITE_SEGMENT_TOKEN') => {
```

2024-08-08 18:26 UTC, HerbertJulio commented on src/plugins/AnalyticsTrackerAdapterPlugin.js
O `makeAnalyticsClient` vai gerar um `throw Error` quando não tiver um token, com isso não vejo a necessidade de criar um novo makeSegmentToken.
Além de que podemos fazer uma verificação neste mesmo ponto se o enviroment foi preenchido.

2024-08-08 18:30 UTC, pauloSF0 commented on src/plugins/factories/analytics-tracking-factory.js
> +  production: 'VITE_PROD_SEGMENT_TOKEN'
done

2024-08-08 18:30 UTC, pauloSF0 commented on src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
> +const makeSut = (segmentToken = 'VITE_STAGE_SEGMENT_TOKEN') => {
done

2024-08-08 19:51 UTC, HerbertJulio submitted a review, later dismissed

2024-08-08 19:53 UTC, vinigfer submitted a review, later dismissed

2024-08-09 13:59 UTC, peterpaulo-azion approved these changes

2024-08-09 14:02 UTC, william-tome approved these changes

2024-08-09 14:03 UTC, peterpaulo-azion approved these changes

2024-08-09 14:13 UTC, HerbertJulio approved these changes

2024-08-09 14:24 UTC, lucasmendes21 approved these changes

2024-08-09 14:32 UTC, merged