[UXE-4458] fix: reworked the behavior logic on the rule engine screen in edge app
aziontech/azion-console-kit pull request #1632
Opened 2024-08-20 18:07 UTC by pauloSF0

…plication

## Bug fix

### Explain what was fixed and the correct behavior.
reworked the behavior logic on the rule engine screen in edge app
### Does this PR introduce UI changes? Add a video or screenshots here.

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] bug: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [x] Application responsiveness was tested to different screen sizes
- [x] New tests are added to prevent the same issue from happening again
- [ ] UI changes are validated by a team designer
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-08-20 19:41 UTC, william-tome requested changes

2024-08-20 19:41 UTC, william-tome commented on src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
> +      default: () => []
Se for required, não passa default ou vice-versa

2024-08-20 19:41 UTC, william-tome commented on src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
> +            <template v-if="behaviorItem.value.name === 'set_origin'">
Não remove a diretiva "else-if", senão o vue vai ter que testar todos os "v-if", e não me parece o cenário aqui

2024-08-21 11:26 UTC, william-tome approved these changes
lgtm

2024-08-21 19:52 UTC, aloisio-m-bastian approved these changes

2024-08-21 19:57 UTC, merged