[ISSUE-4838] feat: adding compare-with-azion POC product
aziontech/azion-console-kit pull request #1732
Opened 2024-09-19 07:28 UTC by robsongajunior

# Adding POC compare-with-azion

- EPIC: https://aziontech.atlassian.net/browse/UXE-4816

<img width="1680" alt="Screenshot 2024-09-19 at 03 22 04" src="https://github.com/user-attachments/assets/214399b8-b155-4412-b68f-3ae921972dd0">

This will be used to analise the result of performed test  from https://www.azion.com/compare-with-azion

2024-09-19 11:33 UTC, lucasmendes21 commented on src/router/routes/compare-with-azion/index.js
> +    testConsolidationService: CompareWithAzionService.testConsolidation,
Deveria ta no padrão ex: CompareWithAzionService.testConsolidationService

2024-09-19 11:34 UTC, lucasmendes21 commented on src/router/routes/compare-with-azion/index.js
> +    getTestById: CompareWithAzionService.getTestById,
Deveria está no padrão ex: getTestByIdService: CompareWithAzionService.getTestByIdService,

2024-09-19 11:35 UTC, lucasmendes21 commented on src/services/axios/makeCompareWithAzionApi.js
> +  // axios.defaults.headers.common['Accept'] = 'application/json; version=3'
Remover comentario.

2024-09-19 11:37 UTC, lucasmendes21 commented on src/services/axios/makeWebpagetestApi.js
> +const makeWebpagetestApi = () => {
makeWebpagetestApiBaseUrl

2024-09-19 11:41 UTC, lucasmendes21 commented on src/services/compare-with-azion/get-test-from-webpagetest.js
> +// import { makeWebpagetestBaseUrlExternal } from './make-base-webpagetest-url'
Remover comentario

2024-09-19 11:44 UTC, lucasmendes21 commented on src/services/compare-with-azion/index.js
> +  getTestById,
getTestByIdService,
  getAllTestsByClientIdService,
  getResultService,
  getResultFromWebpagetestService,
  testConsolidationService

2024-09-19 11:45 UTC, lucasmendes21 commented on src/services/compare-with-azion/index.js
> +  getResult,
Seria interessante getResultCompareWithAzionService

2024-09-19 11:46 UTC, lucasmendes21 commented on src/services/compare-with-azion/test-consolidation.js
> +      body: JSON.stringify({
Usar função de adapt.

2024-09-19 11:47 UTC, lucasmendes21 commented on src/views/CompareWithAzion/CompareView.vue
> +  // Origin Test With Azion
remover comentario

2024-09-19 11:48 UTC, lucasmendes21 commented on src/views/CompareWithAzion/CompareView.vue
> +        return;
Codigo não parece usar o nosso lint

2024-09-19 11:49 UTC, lucasmendes21 commented on src/views/CompareWithAzion/blocks/grade-block.vue
> +    <div v-if="props.items.length === 0 || !props.items" class="text-center py-40">
poderia usar computed

2024-09-19 11:50 UTC, lucasmendes21 commented on src/views/CompareWithAzion/utils/convert-ms-sec.js
> +  let seconds = (ms / 1000).toFixed(3); // Convert ms to seconds and format to 3 decimal places
remover comentario

2024-09-19 11:53 UTC, lucasmendes21 requested changes
Preciso corrigir alguns pontos que mencionei acima.

2024-09-19 12:58 UTC, robsongajunior commented on src/services/compare-with-azion/test-consolidation.js
> +      body: JSON.stringify({
qual funcão? usei a AxiosHttpClientAdapter

2024-09-19 12:58 UTC, robsongajunior commented on src/services/axios/makeCompareWithAzionApi.js
> +  // axios.defaults.headers.common['Accept'] = 'application/json; version=3'
done

2024-09-19 12:59 UTC, robsongajunior commented on src/views/CompareWithAzion/CompareView.vue
> +  // Origin Test With Azion
done

2024-09-19 12:59 UTC, robsongajunior commented on src/views/CompareWithAzion/utils/convert-ms-sec.js
> +  let seconds = (ms / 1000).toFixed(3); // Convert ms to seconds and format to 3 decimal places
done

2024-09-19 12:59 UTC, HerbertJulio commented on src/services/axios/makeCompareWithAzionApi.js
Podemos remover esse make, pois conseguimos passar tanto o baseURL quanto o withCredentials diretamente como parâmetros no makeApi, ajustando o comportamento conforme necessário.

2024-09-19 13:01 UTC, HerbertJulio commented on src/services/axios/makeWebpagetestApi.js
Mesmo caso do makeCompareWithAzionApi

2024-09-19 13:03 UTC, HerbertJulio commented on src/services/compare-with-azion/get-test-from-webpagetest.js
> +  }
Como o id é essencial para o serviço, seria melhor tratar a ausência dele diretamente na view, em vez de chamar o serviço sem esse dado. Além disso, seguimos o padrão de utilizar o parseHttpResponse com os erros default.

2024-09-19 13:04 UTC, HerbertJulio commented on src/services/compare-with-azion/get-test.js
> +  }
Como o id é essencial para o serviço, seria melhor tratar a ausência dele diretamente na view, em vez de chamar o serviço sem esse dado. Além disso, seguimos o padrão de utilizar o parseHttpResponse com os erros default.

2024-09-19 13:05 UTC, HerbertJulio commented on src/services/compare-with-azion/get-test.js
> +export const getTestById = async (id, clientId = undefined) => {
Por default o clientId é undefined quando não passado.
```suggestion
export const getTestById = async (id, clientId) => {
```

2024-09-19 13:10 UTC, HerbertJulio commented on src/services/compare-with-azion/get-test.js
> +  }
Temos o padrão de utilizar `makeSearchParams` no serviço.

2024-09-19 13:15 UTC, HerbertJulio commented on src/services/compare-with-azion/get-test.js
O padrão dos nossos serviços é retornar apenas um único método, que representa o próprio serviço.

2024-09-19 13:22 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +            <div v-if="!errorData">
```suggestion
            <div v-else>
```

2024-09-19 13:22 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +            <div v-if="!errorDataWithAzion">
```suggestion
            <div v-else>
```

2024-09-19 13:24 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  // Origin Test
```suggestion
```

2024-09-19 13:35 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  // Origin Test With Azion
```suggestion
```

2024-09-19 13:37 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  const getQueryString = (name) => new URLSearchParams(window.location.search).get(name)
Com os ajuste no serviço este código acaba não tendo necessidade.
```suggestion
  const getResultFromWebpagetest = async (id) => await props.getResultFromWebpagetest(id)
  const getQueryString = (name) => new URLSearchParams(window.location.search).get(name)
```

2024-09-19 13:41 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  const parseGradeData = (obj) => {
Sugiro colocar um nome de parâmetro mais sugestivo.
```suggestion
  const parseGradeData = (itemCard) => {
```

2024-09-19 13:42 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  }
Esse adpter deveria estar dentro do serviço
```suggestion
```

2024-09-19 13:45 UTC, HerbertJulio commented on src/views/CompareWithAzion/CompareView.vue
> +  })
Recomendo subir grande parte deste 
```suggestion
  onBeforeMount(async () => {
    const testId = getQueryString('id')

    await props.testConsolidationService({
      testId: testId,
      clientId: client_id
    })

    const testById = await props.getTestById(testId, client_id)

    if (!testById.body.length) {
      generalError.value = 'Unavailable comparative tests.'
      return
    }

    getResultFromWebpagetest(testById.body[0].id)
      .then((result) => {
        if (result.body.statusCode !== 200) {
          errorData.value = `Test ${result.body.data.id} is ${result.body.statusText}`
          return
        }

        const medianFirstView = extract.medianRepeatView(result.body)
        resumeData.value = resultparse.grade(result.body)
        gradeData.value = parseGradeData(medianFirstView)
        secureData.value = parseSecureData(medianFirstView)
      })
      .catch(() => {
        errorData.value = 'Not possible to load the Origin test.'
      })

    getResultFromWebpagetest(testById.body[0].id_azion)
      .then((resutWithAzion) => {
        if (resutWithAzion.body.statusCode !== 200) {
          errorDataWithAzion.value = `Test ${resutWithAzion.body.data.id} is ${resutWithAzion.body.statusText}`
          return
        }

        const medianRepeatedViewWithAzion = extract.medianRepeatView(resutWithAzion.body)
        resumeDataWithAzion.value = resultparse.grade(resutWithAzion.body)
        gradeDataWithAzion.value = parseGradeData(medianRepeatedViewWithAzion)
        secureDataWithAzion.value = parseSecureData(medianRepeatedViewWithAzion)
      })
      .catch(() => {
        errorDataWithAzion.value = 'Not possible to load the test with Azion.'
      })
  })
```

2024-09-19 13:46 UTC, HerbertJulio commented on src/views/CompareWithAzion/blocks/grade-block.vue
> +      v-if="props.items.length === 0 || !props.items"
Recomendo colocar em computed
```suggestion
      v-if="hasItems"
```

2024-09-19 13:48 UTC, merged

2024-09-19 13:51 UTC, HerbertJulio commented on src/views/CompareWithAzion/blocks/resume-block.vue
> +  }
const statusTag = (score) => {
  const statusMap = {
    'A+': 'success',
    'A': 'success',
    'B': 'success',
    'C': 'warning',
    'D': 'warning',
    'E': 'danger',
    'F': 'danger'
  };
  
  return statusMap[score] || null;
};

2024-09-19 13:53 UTC, HerbertJulio commented on vite.config.js
> +        },
Se realmente estiver utilizando proxy criar regras no azion.config

2024-09-19 13:58 UTC, aloisio-m-bastian commented on src/views/CompareWithAzion/utils/result-data-parse.js
> +    return hasCart ? true : false
não entendi pq vc utilizou isso aqui

2024-09-19 13:58 UTC, HerbertJulio commented on src/views/CompareWithAzion/blocks/security-block.vue
> +      v-if="Object.keys(props.securityHeaders).length"
v-else

2024-09-19 13:59 UTC, HerbertJulio commented on src/views/CompareWithAzion/blocks/security-block.vue
> +      v-if="!Object.keys(props.securityHeaders).length"
Recomendo criar uma computed ou const com esse retorno

2024-09-19 14:05 UTC, HerbertJulio commented on src/views/CompareWithAzion/utils/convert-ms-sec.js
> +  let seconds = (ms / 1000).toFixed(3)
const seconds

2024-09-19 17:02 UTC, HerbertJulio commented on src/views/CompareWithAzion/utils/result-data-parse.js
> +}
export const gradeTranslate = (score) => {
  if (!score) return ''

  return score >= 90 ? 'A'
       : score >= 80 ? 'B'
       : score >= 70 ? 'C'
       : score >= 60 ? 'D'
       : 'F';
}

2024-09-19 20:10 UTC, HerbertJulio commented on src/views/CompareWithAzion/utils/result-extract.js
Recomendo colocar isso no adpter do serviço

2024-09-24 14:57 UTC, robsongajunior commented on src/views/CompareWithAzion/CompareView.vue
> +          v-if="!generalError"
adicionado v-else

2024-09-24 14:58 UTC, robsongajunior commented on src/views/CompareWithAzion/CompareView.vue
> +            <div v-if="!errorData">
no novo pr já será com v-else

2024-09-24 14:58 UTC, robsongajunior commented on src/views/CompareWithAzion/CompareView.vue
> +            <div v-if="!errorDataWithAzion">
no novo pr já será utilizando v-else

2024-09-24 17:33 UTC, robsongajunior commented on src/views/CompareWithAzion/CompareView.vue
> +  const parseGradeData = (obj) => {
atualizado para: `parseGradeData = (metrics)` e `const parseSecureData = (testResult)`

2024-09-24 17:36 UTC, robsongajunior commented on src/services/compare-with-azion/get-test.js
> +export const getTestById = async (id, clientId = undefined) => {
Feito, validação client_id quando não existente, nem deixa iniciar essas chamadas!

Mudei para ficar no padrão, porém a integridade de parâmetros mesmo não passado deve ser integro e saber dar alguma responta em todas camadas no lugar  de se invalido quebrar.

2024-09-24 17:37 UTC, robsongajunior commented on src/services/compare-with-azion/get-test.js
> +  }
feito

2024-09-24 17:40 UTC, robsongajunior commented on src/views/CompareWithAzion/utils/convert-ms-sec.js
> +  let seconds = (ms / 1000).toFixed(3)
done

2024-09-24 17:42 UTC, robsongajunior commented on src/views/CompareWithAzion/utils/result-data-parse.js
> +    return hasCart ? true : false
funcao removida