[UXE-5544] feat: added marketplace products to sidebar menu with flag
aziontech/azion-console-kit pull request #1864
Opened 2024-10-30 18:57 UTC by peterpaulo-azion

## Pull Request

### What is the new behavior introduced by this PR?
* added marketplace products flag to console
* new itens in sidebar controlled by the flag
* new test case in list menu service

### Does this PR introduce breaking changes?
- [ ] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.
<img width="250" alt="image" src="https://github.com/user-attachments/assets/a34526e9-a84e-4698-8009-fe2132ddc66c">

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [ ] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [ ] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [ ] Code is formatted and linted
- [ ] Tags are added to the PR

#### These changes were tested on the following browsers:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-10-30 21:26 UTC, HerbertJulio commented on src/services/sidebar-menus-services/menus.js
O que acha de criarmos uma nova `prop` que valide se o usuário tem acesso ou não? 
Dessa forma, podemos decidir se o componente deve ser exibido com base nessa validação. Além disso, caso seja necessário adicionar mais alguma opção com flag no futuro, poderemos simplesmente passar essa informação para essa prop.

2024-10-31 09:56 UTC, peterpaulo-azion commented on src/services/sidebar-menus-services/menus.js
Pensei nisso, mas cheguei a conclusão que seria overengineering. Deixaria o código muito complexo pra algo simples e que raramente vamos mexer, que são essas opções do menu e permissões por flag.
Acho que temos muito disso hoje no console então optei por ir pelo simples, limpo e funcional mesmo.

2024-10-31 13:55 UTC, HerbertJulio commented on src/services/sidebar-menus-services/menus.js
Isso não é `overengineering`. Ter uma prop no objeto para controlar a visibilidade facilita o gerenciamento do menu e elimina a necessidade de condicionais (`if`) desnecessários. Por exemplo:

```javascript
{
  label: 'Marketplace',
  icon: 'ai ai-marketplace',
  to: '/marketplace',
  id: 'marketplace',
  visible: showMarketplaceProductsItems
}
```
Além disso, o array de objetos é utilizado diretamente no PrimeMenu, que já suporta a prop `visible`. Isso significa que o controle de visibilidade é nativo, dispensando implementações adicionais.

2024-10-31 14:00 UTC, HerbertJulio requested changes
Recomendo utilizar o suporte da prop visible no PrimeMenu para evitar a criação de condicionais desnecessárias no arquivo `src/services/sidebar-menus-services/menus.js`

2024-10-31 17:56 UTC, peterpaulo-azion commented on src/services/sidebar-menus-services/menus.js
Agora sim ficou claro para mim do que estamos falando, eu tinha entendido algo bem diferente.
Nesse caso, arquivo refatorado.

2024-10-31 17:57 UTC, HerbertJulio approved these changes

2024-10-31 18:00 UTC, peterpaulo-azion commented on src/templates/sidebar-block/index.vue
> +    } else {
Precisa, se não ele vai dar os dois comandos. Não tem mais return ai nesse caso.

2024-10-31 19:15 UTC, vinigfer commented on src/services/sidebar-menus-services/menus.js
> +export function getMenuItens(showMarketplaceProductsItens) {
Nice! Very nice

2024-10-31 19:16 UTC, vinigfer approved these changes

2024-10-31 20:03 UTC, merged