[NO-ISSUE] feat: migrate create edge firewall post method to v4
aziontech/azion-console-kit pull request #1937
Opened 2024-11-18 20:50 UTC by peterpaulo-azion

## Pull Request

### What is the new behavior introduced by this PR?
* migrate post method to v4 in edge firewall
* added unit tests

### Does this PR introduce breaking changes?
- [ ] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [ ] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [ ] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [ ] Code is formatted and linted
- [ ] Tags are added to the PR

#### These changes were tested on the following browsers:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-11-19 12:20 UTC, vinigfer requested changes
Please update with branch freezing to see the tests execution

2024-11-19 14:09 UTC, aloisio-m-bastian requested changes

2024-11-19 14:09 UTC, aloisio-m-bastian commented on src/services/edge-firewall-services/v4/create-edge-firewall-service.js
> +const extractApiError = (httpResponse) => {
A função de extração da mensagem de erro da api não está contemplando todos os casos da doc, da uma olhada no helper que eu criei em helpers/extract-api-error.js

2024-11-19 14:09 UTC, aloisio-m-bastian commented on src/services/edge-firewall-services/v4/create-edge-firewall-service.js
> +    case 401:
outra coisa que eu faria era colocar como default o extract api error, retornar diferente apenas no sucesso (201) e em internal server error (500) para evitarmos termos problemas com aquele toast com a mensagem false para erros em status nao mapeados

2024-11-21 11:55 UTC, aloisio-m-bastian approved these changes

2024-11-21 13:57 UTC, merged