[UXE-5719] feat: migrate create digital certificates
aziontech/azion-console-kit pull request #1950
Opened 2024-11-21 12:05 UTC by pauloSF0

## Pull Request

### What is the new behavior introduced by this PR?

[UXE-5719] feat: migrate create digital certificates

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

https://github.com/user-attachments/assets/3d4b925c-2da6-4728-a4b6-fec03dd9489f

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-11-21 12:32 UTC, aloisio-m-bastian requested changes

2024-11-21 12:32 UTC, aloisio-m-bastian commented on src/services/digital-certificates-services/v4/create-digital-certificates-csr-service.js
> +    case 400:
o ideal é colocar o extract api error como opcao default no switch, remover todos os status e deixar apenas o parser de sucesso (201) e de internal server error (500). Todos errors, exceto o internal server error devem ser parseados a mensagem retornada da api, assim evitamos bug do toast com mensagem false por conta de status não esperados dentro do tratamento do nosso serviço, da uma olhadinha em como eu fiz no create-cache-settings

2024-11-21 13:22 UTC, aloisio-m-bastian approved these changes

2024-11-21 17:50 UTC, lucasmendes21 approved these changes

2024-11-22 13:47 UTC, peterpaulo-azion approved these changes

2024-11-22 13:52 UTC, merged