[UXE-5813] fix: run function show the name of the function and not the instance function
aziontech/azion-console-kit pull request #1975
Opened 2024-11-27 19:55 UTC by pauloSF0

## Pull Request

### What is the new behavior introduced by this PR?
[UXE-5813] fix: run function show the name of the function and not the instance function
### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.

https://github.com/user-attachments/assets/cd7cf146-7e1e-4b5f-af62-f810b557bda3

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (feat, test, refactor, etc)
- [ ] Application responsiveness was tested to different screen sizes
- [x] Code is formatted and linted
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-11-29 17:52 UTC, HerbertJulio submitted a review, later dismissed

2024-12-03 14:17 UTC, aloisio-m-bastian requested changes
não sei se foi alterado em outro pr, mas existe um teste cypress de rules engine que aguarda a resposta da chamada do endpoint, é necessário alterar lá o nome do endpoint para evitar erros e também remover o xfail (motivo por qual o problema não foi acusado em seu pr)

2024-12-04 18:02 UTC, pauloSF0 commented
> não sei se foi alterado em outro pr, mas existe um teste cypress de rules engine que aguarda a resposta da chamada do endpoint, é necessário alterar lá o nome do endpoint para evitar erros e também remover o xfail (motivo por qual o problema não foi acusado em seu pr) <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/107002324/392001550-a273c571-ab16-45fa-b1ed-821e3ecd11c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzUzMzQsIm5iZiI6MTczMzMzNTAzNCwicGF0aCI6Ii8xMDcwMDIzMjQvMzkyMDAxNTUwLWEyNzNjNTcxLWFiMTYtNDVmYS1iMWVkLTgyMWUzZWNkMTFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNzU3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODI4ZjY4MDlhMDgwNTlmZjliZmNkMjQ5ZTU4Y2I2ODUyOWRkNjk4MzZjZDFlM2U0MjAxNjM1MWNlN2M2MGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ln4eHPxitBrvotS5Esxch8TcliVfDdCK4U3RbtO2smg">

2024-12-06 17:50 UTC, aloisio-m-bastian approved these changes

2024-12-06 18:59 UTC, vinigfer commented on cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
>  // TODO: remove xfail tag when the API v4 is fixed
If we remove the xfail, we should also remove this comment
```suggestion
```

2024-12-10 14:35 UTC, aloisio-m-bastian submitted a review, later dismissed

2024-12-10 17:38 UTC, HerbertJulio approved these changes

2024-12-12 17:54 UTC, lucasmendes21 approved these changes

2024-12-12 18:28 UTC, merged