[UXE-1175] theme ajuste em pick list
aziontech/azion-console-kit pull request #534
Opened 2024-01-08 15:25 UTC by gablisb0a

Apenas customiza os elementos para _picklist. 
![Captura de Tela 2024-01-08 às 12 20 04](https://github.com/aziontech/azion-console-kit/assets/95422158/c266b42d-31b3-4f9e-9932-02a484429a8c)

2024-01-08 18:02 UTC, matheus-sunderhus commented on src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
> +            <div class="">
remover o class="" vazion, deixar apenas <div>

2024-01-08 18:02 UTC, matheus-sunderhus commented on src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
> +              <div class="">
remover o class="" vazion, deixar apenas

2024-01-08 18:03 UTC, matheus-sunderhus requested changes
minor changes before merge.

2024-01-09 18:08 UTC, gablisb0a commented on src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
@matheus-sunderhus Feito

2024-01-09 18:08 UTC, gablisb0a reviewed
@matheus-sunderhus Done

2024-01-09 18:14 UTC, matheus-sunderhus approved these changes

2024-01-09 19:06 UTC, HerbertJulio commented on src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
> +              <div class="">
@gablisb0a Seria bom analisar a real necessidade da existência de 2 div's sem class.

2024-01-10 14:35 UTC, matheus-sunderhus approved these changes

2024-01-10 14:36 UTC, merged