[ENG-28788] feat: create function and edit fuction
aziontech/azion-console-kit pull request #553
Opened 2024-01-12 18:58 UTC by lucasmendes21

<img width="1430" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/92529166/74ffb4c8-4ab3-4e15-b6b6-c5f9c747ff12">
<img width="896" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/92529166/7016206e-69be-4364-b1f1-0390958607c7">
<img width="893" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/92529166/13d90a9a-67f4-407f-8e9a-4939e9e3606d">

2024-01-12 19:43 UTC, matheus-sunderhus commented on src/services/edge-application-functions-services/list-edge-application-functions-service.js
> +    statusCode: 200
aqui está fixo status code 200, mas deveria ser o que volta da api em cada caso, para evitar voltar 200 quando na verdade temos error

2024-01-15 13:09 UTC, HerbertJulio commented on src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsOrigins.vue
> +        />
O name tem o * de campo obrigatório, mas não tem nenhuma mensagem de error?
E temos um component para campos com validação que é o **FieldText**:
```suggestion
      <FieldText
          label="Name *"
          name="name"
          :value="name"
        />
```

2024-01-15 13:12 UTC, HerbertJulio commented on src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsOrigins.vue
> +        />
Mesmo que não tenha uma mensagem de error sugiro utilizar o component FieldText, pois a ideia e atualizar os campos dos form's para esses components de field.

2024-01-15 13:37 UTC, matheus-sunderhus commented on src/tests/services/edge-application-functions-services/delete-edge-application-functions-service.test.js
> +  it('should return the API base url to data streaming service', async () => {
should return the API base url to data streaming service => como o teste não retorna nada nem é feito expect sobre retorno após chamar a API, sugiro um título diferente:
should return the API base url to data streaming service -> should call API with correct params. Pois estamos no expect verificando a url e o Method usados.

2024-01-15 13:38 UTC, matheus-sunderhus commented on src/tests/services/edge-application-functions-services/list-functions-service.test.js
> +
mover para dentro do describe.

2024-01-15 13:38 UTC, matheus-sunderhus commented on src/tests/services/edge-application-functions-services/load-function-service.test.js
> +
mover para dentro do descrive

2024-01-15 13:41 UTC, matheus-sunderhus requested changes
ajuste necessários

2024-01-15 14:32 UTC, matheus-sunderhus commented on src/tests/services/edge-application-functions-services/list-functions-service.test.js
> +
mover para dentro do describe

2024-01-15 14:33 UTC, matheus-sunderhus commented on src/tests/services/edge-application-functions-services/load-function-service.test.js
> +})
mover para dentro do describe

2024-01-15 18:40 UTC, HerbertJulio approved these changes

2024-01-15 19:16 UTC, matheus-sunderhus approved these changes

2024-01-15 19:18 UTC, merged