[NO-ISSUE] Fix SelectButton and CreateModal
aziontech/azion-console-kit pull request #601
Opened 2024-01-23 14:44 UTC by cesaroeduardo

Ajustes para resolver um código que estava em SelectButton para afetar o createModal que estava com umas classes desnecessárias.

Antes:
![image](https://github.com/aziontech/azion-console-kit/assets/44036260/664b7818-4b79-4ae0-a5ae-24971d07d839)
![image](https://github.com/aziontech/azion-console-kit/assets/44036260/89991a14-e335-42f3-8eff-f94abbd50b2b)

Depois:
![image](https://github.com/aziontech/azion-console-kit/assets/44036260/c6e40c40-36d4-475f-acac-0a85ed1c9c03)
![image](https://github.com/aziontech/azion-console-kit/assets/44036260/f8a6e939-bbe6-4476-ba15-ee4d9c0e5508)

2024-01-23 14:56 UTC, cesaroeduardo commented
**_I have read the CLA Document and I hereby sign the CLA_**

2024-01-23 17:46 UTC, gablisb0a commented
@cesaroeduardo A cor de Highlight no Create é diferente, essa teria que ser utilizada via pt. a variavel que precisa ser usada para o background do :highlight é $highlightBg ou var(--surface-200).

2024-01-23 18:30 UTC, csfeijo requested changes

2024-01-23 18:30 UTC, csfeijo commented on src/templates/create-modal-block/index.vue
> +            class="w-full whitespace-nowrap h-[38px] flex"
@cesaroeduardo não podemos remover a lógica deste componente, precisamos do :class que aplique a lógica conforme o dado que está chegando. Tem certeza que não precisamos mais desta validação de loading e selectedTab?

2024-01-24 12:22 UTC, cesaroeduardo commented on src/templates/create-modal-block/index.vue
>                label: { class: 'w-full text-left' }
beleza, vou retornar a lógica que faz a verificação do que está selecionado e adicionar um um surface 200 nele

2024-01-24 12:23 UTC, cesaroeduardo commented on src/templates/create-modal-block/index.vue
> +            class="w-full whitespace-nowrap h-[38px] flex"
Realmente cícero, eu achei que não era necessário, mas fiz mais alguns testes agora aqui vi que se não deixar disable o usuário pode clicar em outro menu durante o carregamento e quando carrega ele fica marcado mas não leva para o marcado, de fato, retornando a lógica do disable.

2024-01-24 13:21 UTC, gablisb0a commented on src/templates/create-modal-block/index.vue
> +            class="w-full whitespace-nowrap h-[38px] flex"
De fato, @cesaroeduardo, tem regra de usabilidade nisso. Quando ta em Loading, não é possível interagir com essas camadas.

2024-01-24 16:20 UTC, csfeijo approved these changes

2024-01-24 17:09 UTC, peterpaulo-azion approved these changes

2024-01-24 17:10 UTC, csfeijo approved these changes

2024-01-24 17:11 UTC, merged