[UXE-1573] fix: dateFormat added adjusted
aziontech/azion-console-kit pull request #628
Opened 2024-01-25 20:48 UTC by peterpaulo-azion

Versão em Português:
* Ajustado o formato da data no campo 'customDate'.

English Version:
* Adjusted the date format in the 'customDate' field.

2024-01-25 21:29 UTC, aloisio-m-bastian approved these changes

2024-01-26 12:04 UTC, pauloSF0 approved these changes

2024-01-26 12:36 UTC, csfeijo requested changes
@peterpaulo-azion valida com a @caroldutrasilveira por favor, nosso ambiente todo é em en_US hoje, no RTM atual usamos esse formato de data (mm/dd/yy):

<img width="818" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/25899/4f6b1a09-76f2-4f7a-9a01-bb39788fccc5">

2024-01-26 13:21 UTC, lucasmendes21 approved these changes

2024-01-26 14:09 UTC, peterpaulo-azion commented
PR fechado devido a alinhamentos com Tech Writter.

2024-01-26 14:09 UTC, closed without merging