[UXE-2024] test: added tests to all events services and helpers
aziontech/azion-console-kit pull request #782
Opened 2024-02-27 20:56 UTC by peterpaulo-azion

[UXE-2024](https://aziontech.atlassian.net/browse/UXE-2024)

* added tests to real time events services and helpers
* refactored the query string graphql converter function

<img width="1228" alt="image" src="https://github.com/aziontech/azion-console-kit/assets/109550332/e2ff9803-e7a2-4eea-a9ba-06312f177bd4">

2024-02-28 11:53 UTC, william-tome commented on src/tests/helpers/convert-gql.test.js
Ao invés de repetir as variáveis de filtro e tabela em cada um dos testes, mover esses valores pra um variável de "fixtures" pra facilitar a leitura.
Outro ponto, é que estruturalmente os testes são iguais, com exceção de um. Faz mais sentido, usar cenários e executar it.each ao invés de replicar a mesma lógica.

2024-02-28 11:53 UTC, william-tome commented on src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
> +      ts: 'February 23, 2024 at 06:07 PM'
Deveria estar nas fixtures para manter o padrão

2024-02-28 11:53 UTC, william-tome commented on src/tests/services/real-time-events-service/data-streaming/list-data-streaming.test.js
> +        tsFormat: 'February 23, 2024 at 06:07 PM'
Deveria estar nas fixtures para manter um padrão.
** Verificar outros testes para o mesmo ponto

2024-02-28 11:53 UTC, william-tome commented on src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
> +    ts: new Date('2024-02-23T18:07:25Z').toISOString()
Inserir a string ao invés de uma instância. Em testes, é importante sabe o tipo/formato de dado que está sendo inserido.
** verificar em outros testes o mesmo ponto.

2024-02-28 11:53 UTC, william-tome commented on src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
> +      `  ${datasetName} (`,
Não é impeditivo, mas não vejo motivo pra termos uma variável "datasetName" (assim como nos outros testes), uma vez que o teste em si é referente a esse dataset. Logo o nome pode vir direto na query pra facilitar a leitura.

2024-02-28 11:53 UTC, william-tome commented on src/tests/services/real-time-events-service/intelligent-dns/load-intelligent-dns.test.js
> +        'Address Mapping record (A Record), also known as a DNS host record, stores a hostname and its corresponding IPv4 address.',
Valor estático enquanto outros estão apontando para as fixtures.

2024-02-28 13:13 UTC, peterpaulo-azion commented on src/tests/helpers/convert-gql.test.js
fixtures ajustada para as variáveis que se repetiam.

sobre o it.each, acredito que a gente perde a visibilidade do que realmente está sendo testado.

quando por exemplo, temos esses eachs sem um título explicativo:
![image](https://github.com/aziontech/azion-console-kit/assets/109550332/08e19d31-4502-4240-baba-f9b630cbc7e9)

e esses it's organizado por títulos:
![image](https://github.com/aziontech/azion-console-kit/assets/109550332/de232e7f-2547-4e28-b11b-50d4c3c1e07d)

2024-02-28 13:21 UTC, peterpaulo-azion commented on src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
> +    ts: new Date('2024-02-23T18:07:25Z').toISOString()
Alterado

2024-02-28 13:22 UTC, peterpaulo-azion commented on src/tests/services/real-time-events-service/intelligent-dns/load-intelligent-dns.test.js
> +        'Address Mapping record (A Record), also known as a DNS host record, stores a hostname and its corresponding IPv4 address.',
Esse segue a mesma linha de um valor que foi convertido no processo. Ele não existe no momento de uso das fixtures.

2024-02-28 13:33 UTC, william-tome commented on src/tests/helpers/convert-gql.test.js
Entendo, mas você também pode passar o titulo no each assim como passa as variáveis.

2024-02-28 13:34 UTC, william-tome commented on src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
> +      ts: 'February 23, 2024 at 06:07 PM'
Acho estranho, mas não errado. Foi mais no sentido de recomendação.

2024-03-01 13:42 UTC, lucasmendes21 submitted a review, later dismissed

2024-03-01 13:51 UTC, matheus-sunderhus commented
PR grande, como se trata apenas de melhoria na cobertura e não adiciona funcionalidades. Aconselho a realizarmos o merge após o deploy para revisar com calma o PR.

2024-03-01 13:52 UTC, matheus-sunderhus requested changes
Aguardar o deploy, para os devs realizarem um review melhor, já que o PR tem muitos arquivos e muitos pontos.

2024-03-06 14:30 UTC, aloisio-m-bastian commented on src/services/real-time-events-service/activity-history/load-activity-history.js
> +      activityHistoryEvents.type?.charAt(0).toUpperCase() + activityHistoryEvents.type?.slice(1),
aqui poderia ser usado o helper CaptalizeFirstLetter (apenas sugestão)

2024-03-06 14:41 UTC, aloisio-m-bastian commented on src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
> +      type: fixtures.activityHistory.type,
Poderia testar aqui se o type passou de tudo em minúsculo para primeira letra em maiúsculo

2024-03-06 22:15 UTC, aloisio-m-bastian submitted a review, later dismissed

2024-03-07 15:54 UTC, HerbertJulio commented
@peterpaulo-azion como o @matheus-sunderhus realizou colocou "change requested" é melhor ele analisar o pr.

2024-03-14 19:21 UTC, william-tome commented
@peterpaulo-azion vai precisar abrir um novo PR. Como tem request changes, o merge fica bloqueado.

2024-03-14 19:24 UTC, peterpaulo-azion commented
O PR será transferido para poder ser concluído.

2024-03-14 19:31 UTC, HerbertJulio approved these changes

2024-03-14 20:16 UTC, aloisio-m-bastian approved these changes

2024-03-14 20:18 UTC, merged