[UXE-2053] feat: Insert properties in the event create edge application
aziontech/azion-console-kit pull request #868
Opened 2024-03-08 20:06 UTC by pauloSF0

## Pull Request
[UXE-2053]

### What is the new behavior introduced by this PR?
Insert properties in the event create edge application

### Does this PR introduce breaking changes?
- [x] No
- [ ] Yes 

### Does this PR introduce UI changes? Add a video or screenshots here.
![Captura de Tela 2024-03-08 às 15 24 06](https://github.com/aziontech/azion-console-kit/assets/110847590/b56d0589-fd17-4fe6-9812-5fa353f8227f)

### Does it have a link on Figma?

<hr />

### Checklist

#### Make sure your pull request fits the checklist below (when applicable):

- [x] The issue title follows the format: [ISSUE_CODE] TYPE: TITLE
- [x] Commits are tagged with the right word (fix, feat, test, etc)
- [ ] User inputs are sanitized/protected against malicious attacks
- [x] Tags are added to the PR

#### These changes were tested on the following browsers:
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

2024-03-11 13:30 UTC, lucasmendes21 approved these changes

2024-03-11 19:21 UTC, william-tome commented on src/templates/create-modal-block/index.vue
Revisitar esse nome criado. create/create fica bem estranho

2024-03-11 19:21 UTC, william-tome commented on src/router/routes/edge-application-routes/index.js
> +      path: 'create/:origin?',
Me parece melhor seguir pelo caminho de usar queryParams, pois assim seria mais descritivo evitando gerar dúvidas em quem lê.

2024-03-11 19:21 UTC, william-tome commented on src/templates/create-modal-block/index.vue
> +      to: '/edge-applications/create/create',
```suggestion
      to: '/edge-applications/create?origin=create',
```

2024-03-12 12:12 UTC, william-tome requested changes

2024-03-12 12:12 UTC, william-tome commented on src/views/RealTimeEventsTieredCache/ListView.vue
> +    createPagePath="/edge-applications/create/realTimeEvents"
```suggestion
    createPagePath="/edge-applications/create?origin=realTimeEvents"
```

2024-03-12 12:12 UTC, william-tome commented on src/views/EdgeApplications/ListView.vue
> +        createPagePath="/edge-applications/create/list"
```suggestion
        createPagePath="/edge-applications/create?origin=list"
```

2024-03-12 12:12 UTC, william-tome commented on src/views/EdgeApplications/ListView.vue
> +        createPagePath="/edge-applications/create/list"
```suggestion
        createPagePath="/edge-applications/create?origin=list"
```

2024-03-12 12:12 UTC, william-tome commented on src/views/EdgeApplications/CreateView.vue
> +      from: route.params.origin,
```suggestion
      from: route.query.origin,
```

2024-03-12 13:30 UTC, william-tome submitted a review, later dismissed

2024-03-13 19:55 UTC, william-tome approved these changes

2024-03-14 12:18 UTC, william-tome approved these changes

2024-03-14 12:44 UTC, lucasmendes21 approved these changes

2024-03-14 12:44 UTC, peterpaulo-azion approved these changes

2024-03-14 12:49 UTC, merged